-- Runtime-selectable CJK UI translations shared by every MerfinPlus flavor.
-- Keep keys canonical English; imported payloads and WeakAuras IDs remain untouched.

local MerfinPlus = LibStub("AceAddon-3.0"):GetAddon("MerfinPlus")

local zhCN, zhTW, koKR, jaJP = {}, {}, {}, {}
local function Add(key, cn, tw, kr, jp)
  zhCN[key], zhTW[key], koKR[key], jaJP[key] = cn, tw, kr, jp or key
end

-- Main navigation, common controls and raid cooldowns.
Add("Language", "语言", "語言", "언어")
Add("Close", "关闭", "關閉", "닫기")
Add("Export", "导出", "匯出", "내보내기")
Add("Raid Settings", "团队设置", "團隊設定", "공격대 설정")
Add("Raid Cooldowns", "团队冷却", "團隊冷卻", "공격대 재사용 대기시간")
Add("The Burning Crusade", "燃烧的远征", "燃燒的遠征", "불타는 성전")
Add("Mists of Pandaria", "熊猫人之谜", "潘達利亞之謎", "판다리아의 안개")
Add("General Settings", "常规设置", "一般設定", "일반 설정")
Add("Detected Expansion", "检测到的资料片", "偵測到的資料片", "감지된 확장팩")
Add("Detected expansion: %s", "检测到的资料片：%s", "偵測到的資料片：%s", "감지된 확장팩: %s")
Add("Select Your Aura", "选择你的光环", "選擇你的光環", "오라 선택")
Add("Enable/Disable", "启用/禁用", "啟用/停用", "활성화/비활성화")
Add("Enable", "启用", "啟用", "활성화")
Add("Send Message on Click", "点击时发送消息", "點擊時傳送訊息", "클릭 시 메시지 전송")
Add("Display Settings", "显示设置", "顯示設定", "표시 설정")
Add("These are the standard display filters used by the Raid Cooldown frontend. Additional bar styling remains in WeakAuras.", "这些是团队冷却前端使用的标准显示筛选。额外的条样式仍在 WeakAuras 中设置。", "這些是團隊冷卻前端使用的標準顯示篩選。額外的列樣式仍在 WeakAuras 中設定。", "공격대 재사용 대기시간 프런트엔드에 사용되는 기본 표시 필터입니다. 추가 막대 스타일은 WeakAuras에서 설정합니다.")
Add("Show Yourself", "显示自己", "顯示自己", "자신 표시")
Add("Show When Ready", "就绪时显示", "就緒時顯示", "준비 시 표시")
Add("Show When Dead", "死亡时显示", "死亡時顯示", "사망 시 표시")
Add("Show When Offline", "离线时显示", "離線時顯示", "오프라인 시 표시")
Add("Show Buff Duration", "显示增益持续时间", "顯示增益持續時間", "버프 지속 시간 표시")
Add("Show Ready Indicator", "显示就绪标记", "顯示就緒標記", "준비 표시기 표시")
Add("Dead Color", "死亡颜色", "死亡顏色", "사망 색상")
Add("Raid Subgroups", "团队小队", "團隊小隊", "공격대 하위 그룹")
Add("Advanced Spell Settings", "高级法术设置", "進階法術設定", "고급 주문 설정")
Add("Specialization Display", "专精显示", "專精顯示", "전문화 표시")
Add("Select Spell", "选择法术", "選擇法術", "주문 선택")
Add("Add Spell", "添加法术", "新增法術", "주문 추가")
Add("Delete Spell", "删除法术", "刪除法術", "주문 삭제")
Add("Selected Spell", "已选法术", "已選法術", "선택한 주문")
Add("Spell Name (Optional)", "法术名称（可选）", "法術名稱（選填）", "주문 이름(선택 사항)")
Add("Spell ID (Required)", "法术 ID（必填）", "法術 ID（必填）", "주문 ID(필수)")
Add("Spell ID", "法术 ID", "法術 ID", "주문 ID")
Add("A positive spell ID is required.", "需要正数法术 ID。", "需要正數法術 ID。", "양수 주문 ID가 필요합니다.")
Add("Show DPS", "显示输出", "顯示輸出", "딜러 표시")
Add("Show Tanks", "显示坦克", "顯示坦克", "탱커 표시")
Add("Show Healers", "显示治疗", "顯示治療", "힐러 표시")
Add("Spell Order", "法术顺序", "法術順序", "주문 순서")
Add("Index", "索引", "索引", "인덱스")
Add("Cooldown Activation", "冷却启用", "冷卻啟用", "재사용 대기시간 활성화")
Add("Enable cooldowns by class. Expand a class to configure individual spells.", "按职业启用冷却。展开职业以配置单个法术。", "依職業啟用冷卻。展開職業以設定個別法術。", "직업별로 재사용 대기시간을 활성화합니다. 직업을 펼쳐 개별 주문을 설정하세요.")
Add("Expand", "展开", "展開", "펼치기")
Add("Collapse", "折叠", "摺疊", "접기")
Add("No Raid Cooldown configuration is available for this expansion.", "此资料片没有可用的团队冷却配置。", "此資料片沒有可用的團隊冷卻設定。", "이 확장팩에는 사용 가능한 공격대 재사용 대기시간 설정이 없습니다.")

-- Main pages and shared actions.
Add("Assignments", "分配", "指派", "배정")
Add("General Assignments", "常规分配", "一般指派", "일반 배정")
Add("Raid Assignments", "团队分配", "團隊指派", "공격대 배정")
Add("Tank Assignments", "坦克分配", "坦克指派", "탱커 배정")
Add("Healer Assignments", "治疗分配", "治療指派", "힐러 배정")
Add("Melee Positions", "近战位置", "近戰位置", "근접 위치")
Add("Ranged Positions", "远程位置", "遠程位置", "원거리 위치")
Add("Tank Positions", "坦克位置", "坦克位置", "탱커 위치")
Add("Heal Positions", "治疗位置", "治療位置", "힐러 위치")
Add("Additional Assignments", "额外分配", "額外指派", "추가 배정")
Add("Pre-Boss Groups", "首领前分组", "首領前分組", "보스 전 그룹")
Add("Pre-Boss Groups are not configured yet. This page is reserved for a future update.", "首领前分组尚未配置。此页面保留给将来的更新。", "首領前分組尚未設定。此頁面保留給未來更新。", "보스 전 그룹은 아직 설정되지 않았습니다. 이 페이지는 향후 업데이트용으로 예약되어 있습니다.")
Add("Import replaces the current saved Pre-Boss Groups plan.", "导入将替换当前保存的首领前分组方案。", "匯入會取代目前儲存的首領前分組方案。", "가져오기는 현재 저장된 보스 전 그룹 계획을 교체합니다.")
Add("No Pre-Boss Groups plan imported.", "未导入首领前分组方案。", "尚未匯入首領前分組方案。", "가져온 보스 전 그룹 계획이 없습니다.")
Add("Pre-Boss Groups import failed: %s", "首领前分组导入失败：%s", "首領前分組匯入失敗：%s", "보스 전 그룹 가져오기에 실패했습니다: %s")
Add("Imported %d bosses for %s.", "已为 %s 导入 %d 个首领。", "已為 %s 匯入 %d 個首領。", "%s의 보스 %d개를 가져왔습니다.")
Add("Set %s Group", "设置 %s 小队", "設定 %s 小隊", "%s 그룹 설정")
Add("Set Group", "设置小队", "設定小隊", "그룹 설정")
Add("Raid groups cannot be changed during combat.", "战斗中无法更改团队小队。", "戰鬥中無法變更團隊小隊。", "전투 중에는 공격대 그룹을 변경할 수 없습니다.")
Add("You must be in a raid to set groups.", "必须在团队中才能设置小队。", "必須在團隊中才能設定小隊。", "그룹을 설정하려면 공격대에 있어야 합니다.")
Add("Only the raid leader or a raid assistant can set groups.", "只有团队领袖或团队助理可以设置小队。", "只有團隊隊長或助理可以設定小隊。", "공격대장 또는 공격대 보조만 그룹을 설정할 수 있습니다.")
Add("Only group leaders or raid assistants can broadcast.", "只有小队领袖或团队助理可以广播。", "只有隊長或團隊助理可以廣播。", "파티장 또는 공격대 보조만 전송할 수 있습니다.")
Add("The raid roster APIs are unavailable in this client.", "此客户端中团队名单 API 不可用。", "此客戶端中團隊名單 API 無法使用。", "이 클라이언트에서는 공격대 명단 API를 사용할 수 없습니다.")
Add("No assigned players for %s.", "%s 没有已分配的玩家。", "%s 沒有已指派的玩家。", "%s에 배정된 플레이어가 없습니다.")
Add("Group set successful for %s.", "%s 的小队设置成功。", "%s 的小隊設定成功。", "%s의 그룹 설정에 성공했습니다.")
Add("Group set successful for %s. Groups %d/%d, slots %d/%d; moved %d, skipped %d.", "%s 的小队设置成功。小队 %d/%d，位置 %d/%d；移动 %d，跳过 %d。", "%s 的小隊設定成功。小隊 %d/%d，位置 %d/%d；移動 %d，略過 %d。", "%s의 그룹 설정에 성공했습니다. 그룹 %d/%d, 자리 %d/%d; 이동 %d, 건너뜀 %d.")
Add("No plan players are currently available as uniquely resolved online raid members (missing %d, offline %d, ambiguous %d).", "当前没有可唯一识别的在线计划团队成员（缺失 %d，离线 %d，歧义 %d）。", "目前沒有可唯一識別的線上團隊成員（缺少 %d，離線 %d，歧義 %d）。", "현재 고유하게 확인된 온라인 공격대원이 없습니다(누락 %d, 오프라인 %d, 모호함 %d).")
Add("Group set failed for %s: %s", "%s 的小队设置失败：%s", "%s 的小隊設定失敗：%s", "%s의 그룹 설정에 실패했습니다: %s")
Add("Another group update is still being verified.", "另一个小队更新仍在验证中。", "另一個小隊更新仍在驗證中。", "다른 그룹 업데이트를 아직 확인 중입니다.")
Add("Roster names could not be resolved (missing %d, ambiguous %d).", "无法解析名单名称（缺失 %d，歧义 %d）。", "無法解析名單名稱（缺少 %d，歧義 %d）。", "명단 이름을 확인할 수 없습니다(누락 %d, 모호함 %d).")
Add("%d roster API request(s) failed.", "%d 个名单 API 请求失败。", "%d 個名單 API 請求失敗。", "명단 API 요청 %d개가 실패했습니다.")
Add("%d player(s) left the raid before verification.", "%d 名玩家在验证前离开了团队。", "%d 名玩家在驗證前離開了團隊。", "플레이어 %d명이 확인 전에 공격대를 떠났습니다.")
Add("Roster verification failed (groups %d/%d, slots %d/%d).", "名单验证失败（小队 %d/%d，位置 %d/%d）。", "名單驗證失敗（小隊 %d/%d，位置 %d/%d）。", "명단 확인에 실패했습니다(그룹 %d/%d, 자리 %d/%d).")
Add("Group update requested for %s: %d move(s); missing %d; ambiguous %d; offline %d. Verifying...", "已请求更新 %s 的小队：移动 %d；缺失 %d；歧义 %d；离线 %d。正在验证…", "已要求更新 %s 的小隊：移動 %d；缺少 %d；歧義 %d；離線 %d。正在驗證…", "%s의 그룹 업데이트를 요청했습니다: 이동 %d, 누락 %d, 모호함 %d, 오프라인 %d. 확인 중...")
Add("Group result for %s: groups %d/%d, slots %d/%d; missing %d; ambiguous %d; API errors %d.", "%s 的小队结果：小队 %d/%d，位置 %d/%d；缺失 %d；歧义 %d；API 错误 %d。", "%s 的小隊結果：小隊 %d/%d，位置 %d/%d；缺少 %d；歧義 %d；API 錯誤 %d。", "%s의 그룹 결과: 그룹 %d/%d, 자리 %d/%d; 누락 %d, 모호함 %d, API 오류 %d.")
Add("WoW exposes subgroup moves but no direct intra-group slot API; remaining slot differences are reported.", "WoW 提供小队移动但没有直接的小队内位置 API；会报告剩余的位置差异。", "WoW 提供小隊移動但沒有直接的小隊內位置 API；會回報剩餘的位置差異。", "WoW는 하위 그룹 이동은 제공하지만 그룹 내 자리 API는 제공하지 않습니다. 남은 자리 차이는 보고됩니다.")
Add("Import", "导入", "匯入", "가져오기")
Add("Broadcast", "广播", "廣播", "전송")
Add("Delete", "删除", "刪除", "삭제")
Add("Cancel", "取消", "取消", "취소")
Add("Copy", "复制", "複製", "복사")
Add("Generate", "生成", "產生", "생성")
Add("Press CTRL+C now", "现在按 CTRL+C", "現在按 CTRL+C", "지금 CTRL+C를 누르세요")
Add("Refresh", "刷新", "重新整理", "새로 고침")
Add("Done", "完成", "完成", "완료")
Add("Commands:", "命令：", "命令：", "명령:")
Add("Player", "玩家", "玩家", "플레이어")
Add("Players", "玩家", "玩家", "플레이어")
Add("Select Raid", "选择团队副本", "選擇團隊副本", "공격대 선택")
Add("Select a boss", "选择一个首领", "選擇一個首領", "보스 선택")
Add("Choose a boss from the list.", "从列表中选择一个首领。", "從清單中選擇一個首領。", "목록에서 보스를 선택하세요.")
Add("No imported assignments exist for this boss.", "此首领没有已导入的分配。", "此首領沒有已匯入的指派。", "이 보스에 가져온 배정이 없습니다.")
Add("No imported assignments exist for the selected boss.", "所选首领没有已导入的分配。", "所選首領沒有已匯入的指派。", "선택한 보스에 가져온 배정이 없습니다.")
Add("No General Assignments imports saved.", "没有保存的常规分配导入。", "沒有儲存的一般指派匯入。", "저장된 일반 배정 가져오기가 없습니다.")
Add("No valid General Assignments import is selected.", "未选择有效的常规分配导入。", "未選擇有效的一般指派匯入。", "유효한 일반 배정 가져오기를 선택하지 않았습니다.")
Add("The selected import could not be parsed.", "无法解析所选导入。", "無法解析所選匯入。", "선택한 가져오기를 해석할 수 없습니다.")
Add("Invalid General Assignments string.", "无效的常规分配字符串。", "無效的一般指派字串。", "잘못된 일반 배정 문자열입니다.")
Add("Invalid Raid Assignments string.", "无效的团队分配字符串。", "無效的團隊指派字串。", "잘못된 공격대 배정 문자열입니다.")
Add("Identical import already exists; selected the saved import.", "相同的导入已存在；已选择保存的导入。", "相同的匯入已存在；已選擇儲存的匯入。", "동일한 가져오기가 이미 있습니다. 저장된 가져오기를 선택했습니다.")
Add("General Assignments import saved.", "常规分配导入已保存。", "一般指派匯入已儲存。", "일반 배정 가져오기를 저장했습니다.")
Add("Raid Assignments import saved.", "团队分配导入已保存。", "團隊指派匯入已儲存。", "공격대 배정 가져오기를 저장했습니다.")
Add("Delete the selected General Assignments import?\n\n%s", "删除所选常规分配导入？\n\n%s", "刪除所選一般指派匯入？\n\n%s", "선택한 일반 배정 가져오기를 삭제할까요?\n\n%s")
Add("Delete the selected recorded raid?\n\n%s", "删除所选已记录团队？\n\n%s", "刪除所選已記錄團隊？\n\n%s", "선택한 기록된 공격대를 삭제할까요?\n\n%s")

-- Shared settings, widgets and media.
Add("WoW Sim", "WoW 模拟", "WoW 模擬", "WoW 시뮬레이션")
Add("Media", "媒体", "媒體", "미디어")
Add("Profiles", "配置文件", "設定檔", "프로필")
Add("Settings", "设置", "設定", "설정")
Add("Widget Settings", "小组件设置", "小工具設定", "위젯 설정")
Add("Loot / Roster Export", "战利品 / 名单导出", "戰利品 / 名單匯出", "전리품 / 명단 내보내기")
Add("Show Minimap Icon", "显示小地图图标", "顯示小地圖圖示", "미니맵 아이콘 표시")
Add("Show Assignment Widget", "显示分配小组件", "顯示指派小工具", "배정 위젯 표시")
Add("Show Raid Leader Widget", "显示团队领袖小组件", "顯示團隊隊長小工具", "공격대장 위젯 표시")
Add("Assignment Widget Visibility", "分配小组件可见性", "指派小工具可見性", "배정 위젯 표시")
Add("Raid Leader Widget Visibility", "团队领袖小组件可见性", "團隊隊長小工具可見性", "공격대장 위젯 표시")
Add("Assignment: Show always", "分配：始终显示", "指派：一律顯示", "배정: 항상 표시")
Add("Assignment: Load only in Raid", "分配：仅在团队中加载", "指派：僅在團隊中載入", "배정: 공격대에서만 로드")
Add("Raid Leader: Show always", "团队领袖：始终显示", "團隊隊長：一律顯示", "공격대장: 항상 표시")
Add("Raid Leader: Load only in Raid", "团队领袖：仅在团队中加载", "團隊隊長：僅在團隊中載入", "공격대장: 공격대에서만 로드")
Add("Assignment Widget", "分配小组件", "指派小工具", "배정 위젯")
Add("Raid Leader Widget", "团队领袖小组件", "團隊隊長小工具", "공격대장 위젯")
Add("Raid Leader", "团队领袖", "團隊隊長", "공격대장")
Add("Header Color", "标题颜色", "標題顏色", "헤더 색상")
Add("Header Width", "标题宽度", "標題寬度", "헤더 너비")
Add("Header Height", "标题高度", "標題高度", "헤더 높이")
Add("Header Opacity", "标题不透明度", "標題不透明度", "헤더 불투명도")
Add("Assignment Background Opacity", "分配背景不透明度", "指派背景不透明度", "배정 배경 불투명도")
Add("Header Title X Offset", "标题 X 偏移", "標題 X 位移", "헤더 제목 X 오프셋")
Add("Header Title Y Offset", "标题 Y 偏移", "標題 Y 位移", "헤더 제목 Y 오프셋")
Add("Header Title Size", "标题大小", "標題大小", "헤더 제목 크기")
Add("Header Font", "标题字体", "標題字型", "헤더 글꼴")
Add("Header Title Spacing", "标题字距", "標題字距", "헤더 제목 간격")
Add("Header Icon X Offset", "标题图标 X 偏移", "標題圖示 X 位移", "헤더 아이콘 X 오프셋")
Add("Header Icon Y Offset", "标题图标 Y 偏移", "標題圖示 Y 位移", "헤더 아이콘 Y 오프셋")
Add("Header Icon Size", "标题图标大小", "標題圖示大小", "헤더 아이콘 크기")
Add("Show Icon Logo", "显示图标徽标", "顯示圖示標誌", "아이콘 로고 표시")
Add("Show Border", "显示边框", "顯示邊框", "테두리 표시")
Add("Border Color", "边框颜色", "邊框顏色", "테두리 색상")
Add("Border Thickness", "边框厚度", "邊框粗細", "테두리 두께")
Add("Aligning", "对齐", "對齊", "정렬")
Add("Up", "上", "上", "위")
Add("Down", "下", "下", "아래")
Add("Left", "左", "左", "왼쪽")
Add("Right", "右", "右", "오른쪽")
Add("Drag to move", "拖动以移动", "拖曳以移動", "드래그하여 이동")
Add("Left-click to open settings", "左键点击打开设置", "左鍵點擊開啟設定", "왼쪽 클릭으로 설정 열기")
Add("MerfinPlus Version Check", "MerfinPlus 版本检查", "MerfinPlus 版本檢查", "MerfinPlus 버전 확인")

-- Loot, exports and common semantic labels.
Add("Loot Tracking", "战利品追踪", "戰利品追蹤", "전리품 추적")
Add("Track Loot", "追踪战利品", "追蹤戰利品", "전리품 추적")
Add("Recorded Raids", "已记录团队", "已記錄團隊", "기록된 공격대")
Add("Items:", "物品：", "物品：", "아이템:")
Add("Raid Export", "团队导出", "團隊匯出", "공격대 내보내기")
Add("Guild Export", "公会导出", "公會匯出", "길드 내보내기")
Add("Record rare, epic, and legendary loot in recognized raids. Dungeons are never tracked.", "在已识别团队中记录稀有、史诗和传说战利品。永不追踪地下城。", "在已識別團隊中記錄稀有、史詩與傳說戰利品。永不追蹤地城。", "인식된 공격대의 희귀, 영웅, 전설 전리품을 기록합니다. 던전은 추적하지 않습니다.")
Add("Exports only level %s players for %s, using the Guild Manager roster schema.", "使用 Guild Manager 名单架构，仅为 %s 导出等级 %s 的玩家。", "使用 Guild Manager 名單架構，僅為 %s 匯出等級 %s 的玩家。", "Guild Manager 명단 스키마를 사용하여 %s의 레벨 %s 플레이어만 내보냅니다.")
Add("T5 Raidpack", "T5 团队包", "T5 團隊包", "T5 공격대 팩")
Add("Scanning group...", "正在扫描小队…", "正在掃描隊伍…", "그룹 검사 중...")
Add("You need to be in a group.", "你需要在小队中。", "你必須在隊伍中。", "그룹에 있어야 합니다.")
Add("Main", "主", "主要", "주")
Add("Backup", "备用", "備用", "대체")
Add("Assigned", "已分配", "已指派", "배정됨")
Add("Main Target", "主目标", "主要目標", "주 대상")
Add("Off Target", "副目标", "副目標", "보조 대상")
Add("Tank", "坦克", "坦克", "탱커")
Add("Healer", "治疗", "治療", "힐러")
Add("Damage", "伤害", "傷害", "피해")
Add("Warrior", "战士", "戰士", "전사")
Add("Paladin", "圣骑士", "聖騎士", "성기사")
Add("Hunter", "猎人", "獵人", "사냥꾼")
Add("Rogue", "潜行者", "盜賊", "도적")
Add("Priest", "牧师", "牧師", "사제")
Add("Shaman", "萨满祭司", "薩滿祭司", "주술사")
Add("Mage", "法师", "法師", "마법사")
Add("Warlock", "术士", "術士", "흑마법사")
Add("Druid", "德鲁伊", "德魯伊", "드루이드")
Add("Death Knight", "死亡骑士", "死亡騎士", "죽음의 기사")
Add("Monk", "武僧", "武僧", "수도사")
Add("Bloodlust", "嗜血", "嗜血術", "피의 욕망")
Add("Heroism", "英勇", "영웅심", "영웅심")
Add("Soulstone", "灵魂石", "靈魂石", "영혼석")
Add("Innervate", "激活", "啟動", "정신 자극")
Add("Misdirection", "误导", "誤導", "눈속임")
Add("Star", "星星", "星星", "별")
Add("Circle", "圆形", "圓形", "동그라미")
Add("Diamond", "菱形", "菱形", "다이아몬드")
Add("Triangle", "三角", "三角", "삼각형")
Add("Moon", "月亮", "月亮", "달")
Add("Square", "方块", "方塊", "네모")
Add("Cross", "十字", "十字", "가위표")
Add("Skull", "骷髅", "骷髏", "해골")

-- Raid-pack, profile, media and text-to-speech labels registered after the UI table.
Add("Localization", "本地化", "本地化", "현지화")
Add("Use Specific Localization", "使用指定本地化", "使用指定本地化", "특정 현지화 사용")
Add("Set Text Localization", "设置文本本地化", "設定文字本地化", "텍스트 현지화 설정")
Add("Set Sound Localization", "设置语音本地化", "設定語音本地化", "음성 현지화 설정")
Add("Set Chat Localization", "设置聊天本地化", "設定聊天本地化", "채팅 현지화 설정")
Add("Text to Speech", "文字转语音", "文字轉語音", "텍스트 음성 변환")
Add("Use Specific Voice ID", "使用指定语音 ID", "使用指定語音 ID", "특정 음성 ID 사용")
Add("Voice ID", "语音 ID", "語音 ID", "음성 ID")
Add("Voice Rate", "语速", "語速", "음성 속도")
Add("Volume", "音量", "音量", "볼륨")
Add("Play Test Sound?", "播放测试声音？", "播放測試聲音？", "테스트 소리를 재생할까요?")
Add("Test Text", "测试文本", "測試文字", "테스트 텍스트")
Add("Locale Settings", "语言设置", "語言設定", "언어 설정")
Add("Use Client Locale", "使用客户端语言", "使用用戶端語言", "클라이언트 언어 사용")
Add("Set Locale", "设置语言", "設定語言", "언어 설정")
Add("Existing Profiles", "现有配置文件", "現有設定檔", "기존 프로필")
Add("Current Profile:", "当前配置文件：", "目前設定檔：", "현재 프로필:")
Add("Default", "默认", "預設", "기본값")
Add("New", "新建", "新增", "새로 만들기")
Add("Manage Profiles", "管理配置文件", "管理設定檔", "프로필 관리")
Add("Reset Profile", "重置配置文件", "重設設定檔", "프로필 초기화")
Add("Delete a Profile", "删除配置文件", "刪除設定檔", "프로필 삭제")
Add("Copy From", "复制自", "複製自", "복사 원본")
Add("Import Manager", "导入管理器", "匯入管理器", "가져오기 관리자")
Add("Import WoWSim JSON", "导入 WoWSim JSON", "匯入 WoWSim JSON", "WoWSim JSON 가져오기")
Add("Empty Profile", "空配置文件", "空設定檔", "빈 프로필")
Add("Class", "职业", "職業", "직업")
Add("Specialization", "专精", "專精", "전문화")
Add("Select a specialization.", "请选择一个专精。", "請選擇一個專精。", "전문화를 선택하세요.")
Add("Assign to Current Character", "分配给当前角色", "指派給目前角色", "현재 캐릭터에 배정")
Add("Assigned profiles:", "已分配的配置文件：", "已指派的設定檔：", "배정된 프로필:")
Add("This character has no assigned profiles.", "该角色没有已分配的配置文件。", "此角色沒有已指派的設定檔。", "이 캐릭터에는 배정된 프로필이 없습니다.")
Add("Profile: ", "配置文件：", "設定檔：", "프로필: ")
Add("Delete Profile", "删除配置文件", "刪除設定檔", "프로필 삭제")
Add("Delete this profile?", "删除此配置文件？", "刪除此設定檔？", "이 프로필을 삭제할까요?")
Add("Ready.", "就绪。", "就緒。", "준비됨.")
Add("loading", "加载中", "載入中", "불러오는 중")
Add("Import successful.", "导入成功。", "匯入成功。", "가져오기 성공.")
Add("Invalid JSON.", "无效的 JSON。", "無效的 JSON。", "잘못된 JSON입니다.")
Add("No JSON provided.", "未提供 JSON。", "未提供 JSON。", "JSON이 제공되지 않았습니다.")
Add("Unknown / unsupported class in JSON.", "JSON 中包含未知或不支持的职业。", "JSON 中包含未知或不支援的職業。", "JSON에 알 수 없거나 지원되지 않는 직업이 있습니다.")
Add("C_EncodingUtil not available in this WoW version.", "此 WoW 版本不支持 C_EncodingUtil。", "此 WoW 版本不支援 C_EncodingUtil。", "이 WoW 버전에서는 C_EncodingUtil을 사용할 수 없습니다.")
Add("Show Yourself", "显示自己", "顯示自己", "자신 표시")

-- Remaining dynamic Content.lua labels, messages and Auto-Marker controls.
Add(" (different transport revision)", "（不同的传输版本）", "（不同的傳輸版本）", "(다른 전송 버전)")
Add("%d players at level %d.", "%d 名玩家等级为 %d。", "%d 名玩家等級為 %d。", "플레이어 %d명의 레벨이 %d입니다.")
Add("%s delivery confirmed by %s.", "%s 的传送已由 %s 确认。", "%s 的傳送已由 %s 確認。", "%s 전송을 %s이(가) 확인했습니다.")
Add("%s delivery finished with no receiver confirmations.", "%s 的传送完成，但没有接收者确认。", "%s 的傳送已完成，但沒有接收者確認。", "%s 전송이 수신 확인 없이 완료되었습니다.")
Add("%s delivery rejected by %s: %s.", "%s 的传送被 %s 拒绝：%s。", "%s 的傳送被 %s 拒絕：%s。", "%s 전송을 %s이(가) 거부했습니다: %s.")
Add("+ Suffix", "+ 后缀", "+ 後綴", "+ 접미사")
Add("0 Mana", "0 法力值", "0 法力值", "마나 0")
Add("A reload of the interface is required for this change to take effect.\n\nReload now?", "需要重新加载界面才能使此更改生效。\n\n现在重新加载？", "需要重新載入介面才能使此變更生效。\n\n現在重新載入？", "이 변경 사항을 적용하려면 인터페이스를 다시 불러와야 합니다.\n\n지금 다시 불러올까요?")
Add("Always", "始终", "一律", "항상")
Add("Apply on All", "应用到全部", "套用到全部", "모두에 적용")
Add("Are you sure you want to delete the selected profile?", "确定要删除所选配置文件吗？", "確定要刪除所選設定檔嗎？", "선택한 프로필을 삭제할까요?")
Add("Ashtongue Sorcerer", "灰舌巫师", "灰舌巫師", "잿빛혓바닥 마술사")
Add("Assigned ", "已分配 ", "已指派 ", "배정됨 ")
Add("Assignment addon-message prefixes could not be registered.", "无法注册分配插件消息前缀。", "無法註冊指派插件訊息前綴。", "배정 애드온 메시지 접두사를 등록할 수 없습니다.")
Add("Author: ", "作者：", "作者：", "제작자: ")
Add("Auto-Marker", "自动标记", "自動標記", "자동 징표")
Add("Auto-Marker settings imported successfully.", "自动标记设置导入成功。", "自動標記設定匯入成功。", "자동 징표 설정을 가져왔습니다.")
Add("Berserk", "狂暴", "狂暴", "광폭화")
Add("Boss", "首领", "首領", "보스")
Add("Buff", "增益", "增益", "버프")
Add("Chamber of Command", "指挥大厅", "指揮大廳", "지휘의 방")
Add("Change primary fonts and status bar textures used by Merfin features. A UI reload is required.", "更改 Merfin 功能使用的主要字体和状态条材质。需要重新加载界面。", "變更 Merfin 功能所使用的主要字型與狀態列材質。需要重新載入介面。", "Merfin 기능에서 사용하는 기본 글꼴과 상태 표시줄 텍스처를 변경합니다. UI를 다시 불러와야 합니다.")
Add("Changes the language of text shown directly on auras, such as icons, bars, labels, and other on-aura elements.", "更改直接显示在光环上的文本语言，例如图标、条、标签和其他光环元素。", "變更直接顯示在光環上的文字語言，例如圖示、列、標籤和其他光環元素。", "아이콘, 막대, 레이블 등 오라에 직접 표시되는 텍스트의 언어를 변경합니다.")
Add("Changes the language used for voice lines and sound callouts.", "更改语音台词和声音提示使用的语言。", "變更語音台詞與聲音提示使用的語言。", "음성 대사와 소리 알림에 사용할 언어를 변경합니다.")
Add("Changes the language used when sending Merfin raid and dungeon pack messages to chat.", "更改向聊天发送 Merfin 团队和地下城包消息时使用的语言。", "變更向聊天傳送 Merfin 團隊與地城包訊息時使用的語言。", "Merfin 공격대 및 던전 팩 메시지를 채팅에 보낼 때 사용할 언어를 변경합니다.")
Add("Chase Target", "追击目标", "追擊目標", "대상 추적")
Add("Circle Worldmark - Group 3", "圆形世界标记 - 第 3 组", "圓形世界標記 - 第 3 組", "동그라미 월드마커 - 3그룹")
Add("Circle Worldmark - Group 5", "圆形世界标记 - 第 5 组", "圓形世界標記 - 第 5 組", "동그라미 월드마커 - 5그룹")
Add("Configure raid markers assigned to players targeted by boss mechanics.", "配置分配给被首领机制点名玩家的团队标记。", "設定分配給被首領機制點名玩家的團隊標記。", "보스 메커니즘의 대상이 된 플레이어에게 지정할 공격대 징표를 설정합니다.")
Add("Cooldown", "冷却", "冷卻", "재사용 대기시간")
Add("Cooldown Options", "冷却选项", "冷卻選項", "재사용 대기시간 옵션")
Add("Cooldown settings for this raid will be added later.", "此团队副本的冷却设置将在以后添加。", "此團隊副本的冷卻設定將在稍後新增。", "이 공격대의 재사용 대기시간 설정은 나중에 추가됩니다.")
Add("Cooldown settings imported successfully.", "冷却设置导入成功。", "冷卻設定匯入成功。", "재사용 대기시간 설정을 가져왔습니다.")
Add("Cooldowns", "冷却", "冷卻", "재사용 대기시간")
Add("Copy the settings from one existing profile into the currently active profile.", "将一个现有配置文件的设置复制到当前激活的配置文件。", "將一個現有設定檔的設定複製到目前啟用的設定檔。", "기존 프로필의 설정을 현재 활성 프로필로 복사합니다.")
Add("Create a new empty profile.", "创建新的空配置文件。", "建立新的空設定檔。", "새 빈 프로필을 만듭니다.")
Add("Create an empty WoWSim profile.\nSelect a class, choose a specialization, then click Import.", "创建空的 WoWSim 配置文件。\n选择职业和专精，然后点击导入。", "建立空的 WoWSim 設定檔。\n選擇職業和專精，然後點擊匯入。", "빈 WoWSim 프로필을 만듭니다.\n직업과 전문화를 선택한 뒤 가져오기를 클릭하세요.")
Add("Crushing Shadows", "碾压暗影", "碾壓暗影", "짓이기는 어둠")
Add("Custom Name", "自定义名称", "自訂名稱", "사용자 지정 이름")
Add("Deadly Poison", "致命药膏", "致命毒藥", "맹독")
Add("Delete existing and unused profiles from the database to save space, and cleanup the SavedVariables file.", "从数据库中删除现有且未使用的配置文件以节省空间，并清理 SavedVariables 文件。", "從資料庫中刪除現有且未使用的設定檔以節省空間，並清理 SavedVariables 檔案。", "공간을 절약하고 SavedVariables 파일을 정리하기 위해 기존의 사용하지 않는 프로필을 데이터베이스에서 삭제합니다.")
Add("Delete this item entry.", "删除此物品条目。", "刪除此物品項目。", "이 아이템 항목을 삭제합니다.")
Add("Deletes a profile from the database.", "从数据库中删除配置文件。", "從資料庫中刪除設定檔。", "데이터베이스에서 프로필을 삭제합니다.")
Add("Demon Form", "恶魔形态", "惡魔形態", "악마 형상")
Add("Den of Mortal Delights", "凡人欢愉之巢", "凡人歡愉之巢", "필멸자의 환락의 굴")
Add("Diamond Worldmark - Group 1", "菱形世界标记 - 第 1 组", "菱形世界標記 - 第 1 組", "다이아몬드 월드마커 - 1그룹")
Add("Diamond Worldmark - Group 2", "菱形世界标记 - 第 2 组", "菱形世界標記 - 第 2 組", "다이아몬드 월드마커 - 2그룹")
Add("Diamond Worldmark - Ranged Group 3", "菱形世界标记 - 远程第 3 组", "菱形世界標記 - 遠程第 3 組", "다이아몬드 월드마커 - 원거리 3그룹")
Add("Disable All Bars", "禁用所有条", "停用所有列", "모든 막대 비활성화")
Add("Disable All Cooldowns for Boss", "禁用该首领的所有冷却", "停用此首領的所有冷卻", "이 보스의 모든 재사용 대기시간 비활성화")
Add("Disable All Cooldowns for Enemy", "禁用该敌人的所有冷却", "停用此敵人的所有冷卻", "이 적의 모든 재사용 대기시간 비활성화")
Add("Disabled", "已禁用", "已停用", "비활성화됨")
Add("Display as Bar", "显示为条", "顯示為列", "막대로 표시")
Add("Display on Nameplates", "在姓名板上显示", "在名條上顯示", "이름표에 표시")
Add("Display on Timeline", "在时间线上显示", "在時間軸上顯示", "타임라인에 표시")
Add("Emphasize Cooldowns", "强调冷却", "強調冷卻", "재사용 대기시간 강조")
Add("Emphasize when (sec) left", "剩余多少秒时强调", "剩餘多少秒時強調", "남은 시간(초)에 강조")
Add("Emphasized Bar", "强调条", "強調列", "강조 막대")
Add("Empty", "空", "空", "비어 있음")
Add("Enable all cooldowns for Raid Leader / Assistant", "为团队领袖/助理启用所有冷却", "為團隊隊長/助理啟用所有冷卻", "공격대장/보조의 모든 재사용 대기시간 활성화")
Add("Enable Timeline", "启用时间线", "啟用時間軸", "타임라인 활성화")
Add("Enemy", "敌人", "敵人", "적")
Add("Export / Import", "导出 / 导入", "匯出 / 匯入", "내보내기 / 가져오기")
Add("Export String", "导出字符串", "匯出字串", "내보내기 문자열")
Add("Fatal Attraction", "致命吸引", "致命吸引", "치명적인 끌림")
Add("Fel Rage", "邪能狂怒", "邪能狂怒", "지옥의 분노")
Add("Friendly", "友方", "友方", "아군")
Add("Frost Trap Left Door", "冰霜陷阱左门", "冰霜陷阱左門", "서리 덫 왼쪽 문")
Add("Frost Trap Right Door", "冰霜陷阱右门", "冰霜陷阱右門", "서리 덫 오른쪽 문")
Add("General", "常规", "一般", "일반")
Add("Gorefiend's Vigil", "戈尔菲德的警戒", "高費恩的警戒", "고어핀드의 경계")
Add("Grand Promenade", "大步道", "大步道", "대산책로")
Add("Guild data is unavailable.", "公会数据不可用。", "公會資料無法使用。", "길드 데이터를 사용할 수 없습니다.")
Add("Guild roster requested. Waiting for guild data.", "已请求公会名单。正在等待公会数据。", "已要求公會名單。正在等待公會資料。", "길드 명단을 요청했습니다. 길드 데이터를 기다리는 중입니다.")
Add("Halls of Anguish", "痛苦大厅", "痛苦大廳", "고뇌의 전당")
Add("Here you can change the localization used by Merfin raid and dungeon packs when localization data is available. This is mainly used by Russian-speaking players. For additional localizations, please contact the Merfin staff.", "当本地化数据可用时，你可以在此更改 Merfin 团队和地下城包使用的本地化。此功能主要供俄语玩家使用。如需其他本地化，请联系 Merfin 团队。", "當本地化資料可用時，你可以在此變更 Merfin 團隊與地城包使用的本地化。此功能主要供俄語玩家使用。如需其他本地化，請聯絡 Merfin 團隊。", "현지화 데이터가 있을 때 여기서 Merfin 공격대 및 던전 팩의 현지화를 변경할 수 있습니다. 이 기능은 주로 러시아어 사용자를 위한 것입니다. 추가 현지화가 필요하면 Merfin 팀에 문의하세요.")
Add("Illidari Training Grounds", "伊利达雷训练场", "伊利達瑞訓練場", "일리다리 훈련장")
Add("Impaling Spine", "刺穿脊椎", "刺穿脊椎", "꿰뚫는 가시")
Add("Import String", "导入字符串", "匯入字串", "가져오기 문자열")
Add("Interrupt Left Door", "打断左门", "中斷左門", "왼쪽 문 차단")
Add("Interrupt Right Door", "打断右门", "中斷右門", "오른쪽 문 차단")
Add("Invalid Auto-Marker export string.", "无效的自动标记导出字符串。", "無效的自動標記匯出字串。", "잘못된 자동 징표 내보내기 문자열입니다.")
Add("Invalid Cooldowns export string.", "无效的冷却导出字符串。", "無效的冷卻匯出字串。", "잘못된 재사용 대기시간 내보내기 문자열입니다.")
Add("Items", "物品", "物品", "아이템")
Add("JSON", "JSON", "JSON", "JSON")
Add("Karabor Sewers", "卡拉波下水道", "卡拉伯下水道", "카라보르 하수구")
Add("Lady Malande Interrupts", "玛兰德女士打断", "瑪蘭德女士中斷", "여군주 말란데 차단")
Add("Mage Tank", "法师坦克", "法師坦克", "마법사 탱커")
Add("Melee Positioning", "近战站位", "近戰站位", "근접 위치")
Add("MerfinPlus provides custom fonts, textures, and utilities that enhance or support WeakAuras and other Merfin UI components.", "MerfinPlus 提供自定义字体、材质和工具，用于增强或支持 WeakAuras 及其他 Merfin UI 组件。", "MerfinPlus 提供自訂字型、材質與工具，用於強化或支援 WeakAuras 及其他 Merfin UI 元件。", "MerfinPlus는 WeakAuras 및 다른 Merfin UI 구성 요소를 향상하거나 지원하는 사용자 지정 글꼴, 텍스처 및 유틸리티를 제공합니다.")
Add("Mouseover Marking", "鼠标悬停标记", "滑鼠停留標記", "마우스오버 징표")
Add("Next Prismatic Aura", "下一个棱彩光环", "下一個稜彩光環", "다음 프리즘 오라")
Add("No guild detected.", "未检测到公会。", "未偵測到公會。", "길드를 찾을 수 없습니다.")
Add("No personal %s rows were assigned to you by %s%s.", "%s 没有向你分配个人 %s 行%s。", "%s 沒有向你指派個人 %s 列%s。", "%s이(가) 당신에게 개인 %s 행을 배정하지 않았습니다%s.")
Add("No personal assignments sent: %d not in group, %d offline, %d ambiguous.", "未发送个人分配：%d 不在小队中，%d 离线，%d 有歧义。", "未傳送個人指派：%d 不在隊伍中，%d 離線，%d 有歧義。", "개인 배정을 보내지 않았습니다: 그룹 외 %d, 오프라인 %d, 모호함 %d.")
Add("Parasitic Shadowfiend", "寄生暗影魔", "寄生暗影惡魔", "기생하는 어둠의 마귀")
Add("Paste a WoWSim JSON export below.\nClick Accept, select a specialization icon, then click Import.", "在下方粘贴 WoWSim JSON 导出。\n点击接受，选择专精图标，然后点击导入。", "在下方貼上 WoWSim JSON 匯出。\n點擊接受，選擇專精圖示，然後點擊匯入。", "아래에 WoWSim JSON 내보내기를 붙여넣으세요.\n수락을 클릭하고 전문화 아이콘을 선택한 다음 가져오기를 클릭하세요.")
Add("Phase 4", "第 4 阶段", "第 4 階段", "4단계")
Add("Phase Two Tank Positions", "第二阶段坦克位置", "第二階段坦克位置", "2단계 탱커 위치")
Add("Press Generate to read the guild roster.", "点击生成以读取公会名单。", "點擊產生以讀取公會名單。", "생성을 눌러 길드 명단을 읽으세요.")
Add("Priority", "优先级", "優先順序", "우선순위")
Add("Raid", "团队副本", "團隊副本", "공격대")
Add("Raids", "团队副本", "團隊副本", "공격대")
Add("Received %d personal General Assignment row(s) from %s.", "从 %s 收到 %d 行个人常规分配。", "從 %s 收到 %d 列個人一般指派。", "%s에게서 개인 일반 배정 행 %d개를 받았습니다.")
Add("Received %d personal Raid Assignment row(s) from %s.", "从 %s 收到 %d 行个人团队分配。", "從 %s 收到 %d 列個人團隊指派。", "%s에게서 개인 공격대 배정 행 %d개를 받았습니다.")
Add("Received General Assignments were invalid.", "收到的常规分配无效。", "收到的一般指派無效。", "받은 일반 배정이 잘못되었습니다.")
Add("Received Raid Assignments were invalid.", "收到的团队分配无效。", "收到的團隊指派無效。", "받은 공격대 배정이 잘못되었습니다.")
Add("Rename (display only)", "重命名（仅显示）", "重新命名（僅顯示）", "이름 변경(표시 전용)")
Add("Reset the current profile back to its default values, in case your configuration is broken, or you simply want to start over.", "将当前配置文件重置为默认值，以便在配置损坏或想重新开始时使用。", "將目前設定檔重設為預設值，以便在設定損壞或想重新開始時使用。", "설정이 손상되었거나 다시 시작하려는 경우 현재 프로필을 기본값으로 초기화합니다.")
Add("Reset the current profile to the default", "将当前配置文件重置为默认值", "將目前設定檔重設為預設值", "현재 프로필을 기본값으로 초기화")
Add("Sanctuary of Shadow", "暗影圣所", "暗影聖所", "어둠의 성소")
Add("Select font for element ", "为元素选择字体：", "為元素選擇字型：", "요소의 글꼴 선택: ")
Add("Select how mouseover marking is activated.", "选择如何激活鼠标悬停标记。", "選擇如何啟用滑鼠停留標記。", "마우스오버 징표를 활성화하는 방법을 선택하세요.")
Add("Select one of your currently available profiles.", "选择一个当前可用的配置文件。", "選擇一個目前可用的設定檔。", "현재 사용할 수 있는 프로필 중 하나를 선택하세요.")
Add("Select status bar texture for element ", "为元素选择状态条材质：", "為元素選擇狀態列材質：", "요소의 상태 표시줄 텍스처 선택: ")
Add("Set itemID for ", "设置物品 ID：", "設定物品 ID：", "아이템 ID 설정: ")
Add("Shade of Akama", "阿卡玛之影", "阿卡瑪之影", "아카마의 망령")
Add("Shadow of Death", "死亡之影", "死亡之影", "죽음의 그림자")
Add("Show Berserk only near expiration", "仅在狂暴即将结束时显示", "僅在狂暴即將結束時顯示", "광폭화 만료 직전에만 표시")
Add("Show Berserk when (sec) left", "剩余多少秒时显示狂暴", "剩餘多少秒時顯示狂暴", "광폭화 남은 시간(초)에 표시")
Add("Shrine of Lost Souls", "失落灵魂神殿", "失落靈魂聖殿", "잃어버린 영혼의 사원")
Add("slot ", "槽位 ", "插槽 ", "칸 ")
Add("Soul Drain", "灵魂吸取", "靈魂汲取", "영혼 흡수")
Add("Spirit Shock Interrupt Rotation", "灵魂震击打断轮换", "靈魂震擊中斷輪替", "영혼 충격 차단 순환")
Add("Spite", "怨恨", "怨恨", "원한")
Add("Square Worldmark - Group 1", "方形世界标记 - 第 1 组", "方形世界標記 - 第 1 組", "네모 월드마커 - 1그룹")
Add("Square Worldmark - Ranged Group 2", "方形世界标记 - 远程第 2 组", "方形世界標記 - 遠程第 2 組", "네모 월드마커 - 원거리 2그룹")
Add("Star Worldmark - Group 1", "星形世界标记 - 第 1 组", "星形世界標記 - 第 1 組", "별 월드마커 - 1그룹")
Add("Star Worldmark - Group 2", "星形世界标记 - 第 2 组", "星形世界標記 - 第 2 組", "별 월드마커 - 2그룹")
Add("Star Worldmark - Group 4", "星形世界标记 - 第 4 组", "星形世界標記 - 第 4 組", "별 월드마커 - 4그룹")
Add("Star Worldmark - Ranged Group 1", "星形世界标记 - 远程第 1 组", "星形世界標記 - 遠程第 1 組", "별 월드마커 - 원거리 1그룹")
Add("Subzone", "子区域", "子區域", "하위 지역")
Add("Suffix", "后缀", "後綴", "접미사")
Add("Tank 3", "坦克 3", "坦克 3", "탱커 3")
Add("Temple Summit", "神殿顶峰", "神殿頂峰", "사원 정상")
Add("Test: 13165", "测试：13165", "測試：13165", "테스트: 13165")
Add("The current expansion is not supported.", "不支持当前资料片。", "不支援目前資料片。", "현재 확장팩은 지원하지 않습니다.")
Add("Transition", "转换", "轉換", "전환")
Add("Trash", "小怪", "小怪", "일반몹")
Add("Trash Healer", "小怪治疗", "小怪治療", "일반몹 힐러")
Add("Trash Tank", "小怪坦克", "小怪坦克", "일반몹 탱커")
Add("Triangle Worldmark - Group 2", "三角世界标记 - 第 2 组", "三角世界標記 - 第 2 組", "삼각형 월드마커 - 2그룹")
Add("Use Custom Name", "使用自定义名称", "使用自訂名稱", "사용자 지정 이름 사용")
Add("Vanish", "消失", "消失", "소멸")
Add("Version:", "版本：", "版本：", "버전:")
Add("Warlock Tank", "术士坦克", "術士坦克", "흑마법사 탱커")
Add("Wave Mobs", "波次小怪", "波次小怪", "파도 몬스터")
Add("You can change the active database profile, so you can have different settings for every character.", "你可以更改当前数据库配置文件，以便为每个角色使用不同设置。", "你可以變更目前資料庫設定檔，以便為每個角色使用不同設定。", "활성 데이터베이스 프로필을 변경하여 캐릭터마다 다른 설정을 사용할 수 있습니다.")
Add("You can check for available voice IDs by checking \"Play Test Sound?\" option", "可通过“播放测试声音？”选项检查可用的语音 ID。", "可透過「播放測試聲音？」選項檢查可用的語音 ID。", "\"테스트 소리를 재생할까요?\" 옵션으로 사용 가능한 음성 ID를 확인할 수 있습니다.")
Add("You can either create a new profile by entering a name in the editbox, or choose one of the already existing profiles.", "你可以在编辑框中输入名称创建新配置文件，或选择已有配置文件。", "你可以在編輯框中輸入名稱建立新設定檔，或選擇已有設定檔。", "입력창에 이름을 입력해 새 프로필을 만들거나 기존 프로필 중 하나를 선택할 수 있습니다.")
Add("Zerevor Interrupts", "泽瑞沃尔打断", "澤瑞沃爾中斷", "제레보르 차단")

Add("Header Font", "标题字体", "標題字體", "제목 글꼴")
Add("Aligning", "对齐", "對齊", "정렬")
Add("Up", "上", "上", "위")
Add("Down", "下", "下", "아래")
Add("Left", "左", "左", "왼쪽")
Add("Right", "右", "右", "오른쪽")
Add("Assignment Widget Visibility", "分配窗口可见性", "指派視窗可見性", "배정 위젯 표시")
Add("Raid Leader Widget Visibility", "团队领袖窗口可见性", "團隊領袖視窗可見性", "공격대장 위젯 표시")

-- Japanese is a selectable MerfinPlus language (WoW does not expose it as a
-- normal client locale). Keep the core controls native while remaining keys
-- safely fall back to their canonical English wording until translated.
local japaneseCore = {
  ["Language"] = "言語", ["Close"] = "閉じる", ["Export"] = "エクスポート",
  ["Assignments"] = "割り当て", ["Raid Settings"] = "レイド設定",
  ["Raid Cooldowns"] = "レイドのクールダウン", ["General Settings"] = "一般設定",
  ["Settings"] = "設定", ["Widget Settings"] = "ウィジェット設定",
  ["Loot / Roster Export"] = "戦利品 / ロスターのエクスポート",
  ["Profiles"] = "プロファイル", ["Media"] = "メディア",
  ["Enable"] = "有効化", ["Disable"] = "無効化", ["Save"] = "保存",
  ["Cancel"] = "キャンセル", ["Delete"] = "削除", ["Import"] = "インポート",
  ["Select Your Aura"] = "オーラを選択", ["Detected Expansion"] = "検出された拡張",
  ["Display Settings"] = "表示設定", ["Cooldown Activation"] = "クールダウンの有効化",
  ["Localization"] = "ローカライゼーション", ["Text to Speech"] = "テキスト読み上げ",
  ["General Assignments"] = "一般割り当て", ["Raid Assignments"] = "レイド割り当て",
  ["Tank Assignments"] = "タンク割り当て", ["Healer Assignments"] = "ヒーラー割り当て",
  ["Select Raid"] = "レイドを選択", ["Select a boss"] = "ボスを選択",
  ["Choose a boss from the list."] = "リストからボスを選択してください。",
  ["Show Minimap Icon"] = "ミニマップアイコンを表示",
  ["The Burning Crusade"] = "燃え尽きる太陽の遠征",
  ["Mists of Pandaria"] = "パンダリアの霧",
  ["Use Specific Localization"] = "特定のローカライゼーションを使用",
  ["Set Text Localization"] = "テキストの言語を設定",
  ["Set Sound Localization"] = "音声の言語を設定",
  ["Set Chat Localization"] = "チャットの言語を設定",
  ["Text to Speech"] = "テキスト読み上げ", ["Use Specific Voice ID"] = "特定の音声 ID を使用",
  ["Voice ID"] = "音声 ID", ["Voice Rate"] = "読み上げ速度", ["Volume"] = "音量",
  ["Play Test Sound?"] = "テスト音声を再生しますか？", ["Test Text"] = "テストテキスト",
  ["Enable/Disable"] = "有効化/無効化", ["Send Message on Click"] = "クリック時にメッセージを送信",
  ["Show Yourself"] = "自分を表示", ["Show When Ready"] = "準備完了時に表示",
  ["Show When Dead"] = "死亡時に表示", ["Show When Offline"] = "オフライン時に表示",
  ["Show Buff Duration"] = "バフの残り時間を表示", ["Show Ready Indicator"] = "準備完了の表示",
  ["Dead Color"] = "死亡時の色", ["Raid Subgroups"] = "レイドサブグループ",
  ["Advanced Spell Settings"] = "高度な呪文設定", ["Specialization Display"] = "専門化の表示",
  ["Select Spell"] = "呪文を選択", ["Add Spell"] = "呪文を追加", ["Delete Spell"] = "呪文を削除",
  ["Selected Spell"] = "選択した呪文", ["Spell Name (Optional)"] = "呪文名（任意）",
  ["Spell ID (Required)"] = "呪文 ID（必須）", ["Spell Order"] = "呪文の順序",
  ["Enable cooldowns by class. Expand a class to configure individual spells."] = "クラスごとにクールダウンを有効化します。クラスを展開して個別の呪文を設定してください。",
  ["Auto-Marker"] = "自動マーカー", ["Enemy"] = "敵", ["Friendly"] = "味方",
  ["Raid"] = "レイド", ["Subzone"] = "区画", ["Priority"] = "優先度",
  ["Mouseover Marking"] = "マウスオーバーマーキング", ["Always"] = "常に",
  ["Disabled"] = "無効", ["Select how mouseover marking is activated."] = "マウスオーバーマーキングを有効にする方法を選択してください。",
  ["Configure raid markers assigned to players targeted by boss mechanics."] = "ボスギミックの対象プレイヤーに割り当てるレイドマーカーを設定します。",
  ["Auto-Marker settings imported successfully."] = "自動マーカー設定をインポートしました。",
  ["Invalid Auto-Marker export string."] = "無効な自動マーカーのエクスポート文字列です。",
  ["Tank Assignments"] = "タンク割り当て", ["Healer Assignments"] = "ヒーラー割り当て",
  ["Melee Positions"] = "近接位置", ["Ranged Positions"] = "遠隔位置",
  ["Tank Positions"] = "タンク位置", ["Heal Positions"] = "ヒーラー位置",
  ["Additional Assignments"] = "追加割り当て", ["Pre-Boss Groups"] = "ボス前グループ",
  ["Main"] = "メイン", ["Backup"] = "予備", ["Assigned"] = "割り当て済み",
  ["Header Font"] = "見出しフォント", ["Aligning"] = "配置",
  ["Up"] = "上", ["Down"] = "下", ["Left"] = "左", ["Right"] = "右",
  ["Assignment Widget Visibility"] = "割り当てウィジェットの表示",
  ["Raid Leader Widget Visibility"] = "レイドリーダーウィジェットの表示",
  ["Berserk"] = "バーサーク", ["Chase Target"] = "標的追跡",
  ["Ashtongue Sorcerer"] = "灰舌の魔術師", ["0 Mana"] = "マナ 0",
  ["Transition"] = "移行", ["Next Prismatic Aura"] = "次のプリズムのオーラ",
  ["Vanish"] = "消失", ["Demon Form"] = "悪魔形態", ["Phase 4"] = "フェーズ 4",
  ["Impaling Spine"] = "貫通する棘", ["Crushing Shadows"] = "押しつぶす影",
  ["Shadow of Death"] = "死の影", ["Fel Rage"] = "邪悪な憤怒",
  ["Spite"] = "悪意", ["Soul Drain"] = "魂の吸収",
  ["Fatal Attraction"] = "致命的な魅了", ["Deadly Poison"] = "致死毒",
  ["Parasitic Shadowfiend"] = "寄生する影魔", ["Test: 13165"] = "テスト: 13165",
}
for key, value in pairs(japaneseCore) do
  jaJP[key] = value
end

-- Assignment catalogs use stable English boss IDs. Keep their presentation
-- names in the same locale registry as the rest of the UI.
local boss = {}
local function Boss(key, cn, tw, kr, jp)
  boss[key] = { zhCN = cn, zhTW = tw, koKR = kr, jaJP = jp }
end
Boss("High Warlord Naj'entus", "高阶督军纳因图斯", "高階督軍納因圖斯", "대장군 나젠투스", "大将軍ナジェントゥス")
Boss("Supremus", "苏普雷姆斯", "蘇普雷姆斯", "궁극의 심연", "スプレマス")
Boss("Shade of Akama", "阿卡玛之影", "阿卡瑪之影", "아카마의 망령", "アカマの影")
Boss("Teron Gorefiend", "塔隆·血魔", "泰朗·血魔", "테론 고어핀드", "テロン・ゴアフィーンド")
Boss("Gurtogg Bloodboil", "古尔图格·血沸", "古爾圖格·血沸", "구르토그 블러드보일", "グルトッグ・ブラッドボイル")
Boss("Reliquary of Souls", "灵魂之匣", "靈魂聖匣", "영혼의 성물함", "ソウルの具現者")
Boss("Mother Shahraz", "莎赫拉丝主母", "莎赫拉絲主母", "대모 샤라즈", "マザー・シャーラズ")
Boss("The Illidari Council", "伊利达雷议会", "伊利達瑞議會", "일리다리 의회", "イリダリ評議会")
Boss("Illidan Stormrage", "伊利丹·怒风", "伊利丹·怒風", "일리단 스톰레이지", "イリダン・ストームレイジ")
Boss("Rage Winterchill", "雷基·冬寒", "瑞齊·凜冬", "격노한 윈터칠", "レイジ・ウィンターコールド")
Boss("Anetheron", "安纳塞隆", "安納塞隆", "아네테론", "アネセロン")
Boss("Kaz'rogal", "卡兹洛加", "卡茲洛加", "카즈로갈", "카즈로갈")
Boss("Azgalor", "阿兹加洛", "阿茲加洛", "아즈갈로", "아즈갈로")
Boss("Archimonde", "阿克蒙德", "阿克蒙德", "아키몬드", "아키몬드")
Boss("Attumen the Huntsman", "猎手阿图门", "獵人阿圖曼", "사냥꾼 아튜멘", "狩馬アットーメン")
Boss("Moroes", "莫罗斯", "莫洛斯", "모로스", "モロース")
Boss("Maiden of Virtue", "贞节圣女", "貞潔聖女", "고결의 여신", "貞節の乙女")
Boss("Opera Event", "歌剧院事件", "歌劇院事件", "오페라 이벤트", "オペラ・イベント")
Boss("The Curator", "馆长", "館長", "전시 관리인", "キュレーター")
Boss("Terestian Illhoof", "特雷斯坦·邪蹄", "泰瑞斯提安·疫蹄", "테레스티안 일후프", "テレスティアン・イリーフ")
Boss("Netherspite", "虚空幽龙", "尼德斯", "황천의 원령", "ネザースパイト")
Boss("Prince Malchezaar", "玛克扎尔王子", "莫克札王子", "공작 말체자르", "マルチェザール公爵")
Boss("Nightbane", "夜之魇", "夜禍", "황혼의 파멸", "ナイトベイン")
Boss("Al'ar", "奥", "歐爾", "알아르", "アルアール")
Boss("Void Reaver", "空灵机甲", "虛無搶奪者", "공허의 절단기", "ヴォイド・リーヴァー")
Boss("High Astromancer Solarian", "大星术师索拉瑞恩", "高階占星術師索拉瑞恩", "대점성술사 솔라리안", "大星術師ソラリアン")
Boss("Kael'thas Sunstrider", "凯尔萨斯·逐日者", "凱爾薩斯·逐日者", "캘타스 선스트라이더", "ケルサス・サンストライダー")
Boss("Hydross the Unstable", "不稳定的海度斯", "不穩定的海卓司", "불안정한 히드로스", "不安定なヒュドロス")
Boss("The Lurker Below", "鱼斯拉", "深淵潛伏者", "심연의 잠복꾼", "深淵の領主カルドラン")
Boss("Leotheras the Blind", "盲眼者莱欧瑟拉斯", "盲目者李奧薩拉斯", "눈먼 레오테라스", "盲目のレオテラス")
Boss("Fathom-Lord Karathress", "深水领主卡拉瑟雷斯", "海底霸主卡拉薩瑞斯", "심연의 군주 카라드레스", "深淵の王カラザレス")
Boss("Morogrim Tidewalker", "莫洛格里·踏潮者", "莫洛葛利·踏潮者", "모로그림 타이드워커", "モログリム・タイドウォーカー")
Boss("Lady Vashj", "瓦丝琪女士", "瓦許女士", "여군주 바쉬", "レディ・ヴァッシュ")
Boss("Kalecgos", "卡雷苟斯", "卡雷苟斯", "칼렉고스", "カレクゴス")
Boss("Brutallus", "布鲁塔卢斯", "布魯塔盧斯", "브루탈루스", "ブルタラス")
Boss("Felmyst", "菲米丝", "魔霧龍", "지옥안개", "フェルミスト")
Boss("Eredar Twins", "艾瑞达双子", "艾瑞達雙子", "에레다르 쌍둥이", "エレダールの双子")
Boss("M'uru", "穆鲁", "穆魯", "므우루", "ムル")
Boss("Kil'jaeden", "基尔加丹", "基爾加丹", "킬제덴", "キルジェデン")

local raid = {}
local function Raid(key, cn, tw, kr, jp)
  raid[key] = { zhCN = cn, zhTW = tw, koKR = kr, jaJP = jp }
end
Raid("Karazhan", "卡拉赞", "卡拉贊", "카라잔", "カラザン")
Raid("TK/SSC", "风暴要塞 / 毒蛇神殿", "風暴要塞 / 毒蛇神殿", "폭풍우 요새 / 불뱀 제단", "テンペスト・キープ / サーペントシャイン洞窟")
Raid("The Eye", "风暴要塞", "風暴要塞", "폭풍우 요새", "目")
Raid("Tempest Keep", "风暴要塞", "風暴要塞", "폭풍우 요새", "テンペスト・キープ")
Raid("Serpentshrine Cavern", "毒蛇神殿", "毒蛇神殿洞穴", "불뱀 제단", "サーペントシャイン洞窟")
Raid("Black Temple", "黑暗神殿", "黑暗神廟", "검은 사원", "ブラック・テンプル")
Raid("Battle for Mount Hyjal", "海加尔山之战", "海加爾山之戰", "하이잘 산 전투", "ハイジャル山の戦い")
Raid("Hyjal Summit", "海加尔山", "海加爾山", "하이잘 정상", "ハイジャル山")
Raid("Sunwell Plateau", "太阳之井高地", "太陽之井高地", "태양샘 고원", "太陽の井戸高原")

MerfinPlus.CJKContentTranslations = { boss = boss, raid = raid }

MerfinPlus.CJKTranslations = {
  zhCN = zhCN,
  zhTW = zhTW,
  koKR = koKR,
  jaJP = jaJP,
}
