-- MerfinPlus saved variable defaults and default media helpers.

local MerfinPlus = LibStub("AceAddon-3.0"):GetAddon("MerfinPlus")

MerfinPlus.defaults = {
  profile = {
    minimapButton = {
      minimapPos = 225,
      showIcon = true,
    },
    pullStartTime = 0,
    pullExpTime = 0,
    pullTotalTime = 0,
    pullSenderName = "Unknown",
    breakStartTime = 0,
    breakExpTime = 0,
    breakTotalTime = 0,
    breakSenderName = "Unknown",
    lfgStartTimer = 0,
    lfgExpTimer = 0,

    font1 = MerfinPlus.GetDefaultFont(),
    font2 = MerfinPlus.GetDefaultFont("bold"),
    font3 = MerfinPlus.GetDefaultRaidFont(),
    font4 = MerfinPlus.GetDefaultRaidFont("bold"),
    bar1 = "MerfinMainDark",
    bar2 = "MerfinMain",
    bar3 = "MerfinMainDark",

    useSpecificLocalization = false,
    rpTextLocale = GAME_LOCALE or GetLocale(),
    rpSoundLocale = GAME_LOCALE or GetLocale(),
    rpChatLocale = GAME_LOCALE or GetLocale(),
    ttsEnabled = true,
    ttsApplyAll = true,
    ttsVolume = 30,
    ttsUseSpecificVoiceID = false,
    ttsVoiceID = 1,
    ttsVoiceRate = 2,
    ttsTestText = "Merfin Test Sound",
    enableTBCWaSettingsOnMoP = false,

    readyCheck = {
      enabled = false,
      enableSlashMerfinRT = false,
      leaderOnly = false,
      assistantOnly = false,
      displayDuration = 15,
      fontSize = 14,
      sortByClass = false,
      sortByName = false,
      reportFood = false,
      reportFlask = false,
      reportScrolls = false,
      reportMotw = false,
      reportIntellect = false,
      reportAttackPower = false,
      reportStamina = false,
      reportSpirit = false,
      reportArmor = false,
      reportShadow = false,
      reportMight = false,
      reportWisdom = false,
      reportKings = false,
      reportSalvation = false,
      showExpiring = true,
      showFoodColumn = true,
      showFlaskColumn = true,
      showScrollsColumn = true,
      showMotwColumn = true,
      showIntellectColumn = true,
      showAttackPowerColumn = true,
      showStaminaColumn = true,
      showSpiritColumn = true,
      showArmorColumn = true,
      showShadowColumn = true,
      showMightColumn = true,
      showWisdomColumn = true,
      showKingsColumn = true,
      showSalvationColumn = true,
      showDurabilityColumn = true,
      showMerfinPlusColumn = true,
      showT5Column = true,
      showT6Column = true,
      showT6AColumn = true,
      windowWidth = 940,
      windowHeight = 820,
      windowX = 0,
      windowY = 0,
    },

    raidCooldowns = {
      general = {
        enableTimeline = false,
        disableCD = false,
        emphasizedBar = true,
        emphasizedOn = 7,
        berserkOnlyShow = false,
        berserkShowOn = 60,
        enableRL = false,
      },
      raids = {
        serpentshrineCavern = {
          ["Trash-SSC"] = {
            AcidGeyser = { displayBar = true },
            ShieldCharge = { displayBar = true },
            Silence = { displayBar = true },
            SporeQuake = { displayBar = true },
          },
        },
        tempestKeep = {},
        blackTemple = {
          ["602"] = {
            MoltenPunch = { displayBar = false, displayTimeline = false },
          },
          ["604"] = {
            Incinerate = { displayBar = false, displayTimeline = false },
          },
          ["605"] = {
            ArcingSmash = { displayBar = false, displayTimeline = false, displayNameplate = true },
            BewilderingStrike = { displayBar = false, displayTimeline = false },
            FelAcidBreath = { displayBar = false, displayTimeline = false },
            Eject = { displayBar = false, displayTimeline = false },
          },
          ["607"] = {
            PrismaticAura = { displayBar = false, displayTimeline = false },
          },
          ["608"] = {
            DampenMagic = { displayBar = false, displayTimeline = false },
            Blizzard = { displayBar = false, displayTimeline = false },
            Consecration = { displayBar = false, displayTimeline = false },
            Flamestrike = { displayBar = false, displayTimeline = false },
          },
          ["609"] = {
            Blaze = { displayBar = false, displayTimeline = false, displayNameplate = true },
            FlameBlast = { displayBar = false, displayTimeline = false, displayNameplate = true },
            DarkBarrage = { displayBar = false, displayTimeline = false },
            FlameCrash = { displayBar = false, displayTimeline = false },
          },
          ["Trash-BT"] = {
            __disabledNpcs = {
              [22845] = true, [22846] = true, [22847] = true, [22848] = true,
              [22849] = true, [22853] = true, [22869] = true, [22873] = true,
              [22874] = true, [22875] = true, [22876] = true, [22881] = true,
              [22945] = true, [22953] = true, [22956] = true, [22963] = true,
              [23030] = true, [23236] = true, [23237] = true, [23330] = true,
              [23374] = true, [23397] = true, [23400] = true, [23402] = true,
              [23403] = true,
            },
            AshtongueBattlelordEnrage = { displayNameplate = false },
            Bloodlust = { displayNameplate = false },
            BonechewerBehemothEnrage = { displayNameplate = false },
            ChainHeal = { displayNameplate = false },
            CloakOfShadows = { displayNameplate = false },
            ConcussionBlow = { displayNameplate = false },
            CurseOfMending = { displayNameplate = false },
            CurseOfTheBleakheart = { displayNameplate = false },
            DebilitatingSpray = { displayNameplate = false },
            ElectricSpur = { displayNameplate = false },
            Fear = { displayNameplate = false },
            FelStomp = { displayBar = true },
            Felfire = { displayNameplate = false },
            FieryComet = { displayNameplate = false },
            FlameShock = { displayNameplate = false },
            FreezingTrap = { displayNameplate = false },
            FrostShock = { displayNameplate = false },
            Gouge = { displayNameplate = false },
            GreaterHeal = { displayNameplate = false },
            IllidariFlames = { displayNameplate = false },
            Jab = { displayNameplate = false },
            LightningProd = { displayNameplate = false },
            Meteor = { displayBar = true },
            PoisonBoltVolley = { displayNameplate = false },
            PoisonSpit = { displayNameplate = false },
            PriestessOfDelightHolyNova = { displayNameplate = false },
            RainOfChaos = { displayNameplate = false },
            SearingTotem = { displayNameplate = false },
            Shadowstep = { displayNameplate = false },
            ShellShield = { displayNameplate = false },
            SilencingShot = { displayNameplate = false },
            SkeletonShot = { displayNameplate = false },
            SpellAbsorption = { displayNameplate = false },
            SummonShadowfiends = { displayNameplate = false },
            SummonWindfuryTotem = { displayNameplate = false },
            WaterSpit = { displayNameplate = false },
            WingClip = { displayNameplate = false },
          },
        },
        hyjalSummit = {
          ["618"] = {
            FrostArmor = { displayBar = false, displayTimeline = false },
          },
          ["620"] = {
            Cripple = { displayBar = false, displayTimeline = false },
            MalevolentCleave = { displayBar = false, displayTimeline = false },
          },
          ["622"] = {
            DoomfireStrike = { displayBar = false, displayTimeline = false },
            GripOfTheLegion = { displayBar = false, displayTimeline = false },
          },
          ["Trash-Hyjal"] = {
            __disabledNpcs = {
              [17895] = true, [17898] = true, [17899] = true,
              [17905] = true, [17907] = true, [17916] = true,
            },
            Waves = { displayBar = true, displayNameplate = false },
          },
        },
      },
    },

    raidAutoMarker = MerfinPlus.AutoMarkerDefaults,

    simImports = {},
  },
  global = {
    internalVersion = 0,
    uiTheme = "origin",
    raidCooldownTracker = {
      schemaVersion = 1,
      expansions = {},
    },
    uiLocale = (({
      enUS = true, deDE = true, frFR = true, esES = true,
      esMX = true, ptBR = true, itIT = true, ruRU = true,
    })[GAME_LOCALE or GetLocale()] and (GAME_LOCALE or GetLocale())) or "enUS",
    companion = {
      weakAuras = {
        selected = {},
        updatedAt = 0,
        revision = 0,
        source = "",
      },
    },
    wowSims = {
      internalVersion = 0,
      profiles = {},
      assigned = {},
      defaults = nil,
    },
    exports = {
      trackLoot = false,
      lootSessions = {},
    },
    assignments = {
      generalImports = {},
      generalCollapsedSections = {},
      activePersonalGeneralImportId = nil,
      preBossPlanStore = {
        schemaVersion = 1,
      },
      raidImports = {},
      raidCollapsedSections = {},
      activeRaidImportByGroup = {},
      activePersonalRaidImportId = nil,
      activePersonalRaidBossKey = nil,
      viewState = {
        activeMainNav = "raidPack",
        activeAssignmentsTab = "general",
        activeRaidCooldownsTab = "general",
        raidAssignments = {
          selectedGroup = nil,
          selectedBossKey = nil,
        },
      },
      showMinimapIcon = true,
      showAssignmentWidget = false,
      assignmentWidgetShowAlways = false,
      assignmentWidgetLoadOnlyInRaid = true,
      assignmentWidgetAlignment = "Down",
      assignmentWidgetX = 260,
      assignmentWidgetY = -120,
      assignmentWidgetPinned = false,
      assignmentWidgetHeaderR = 0,
      assignmentWidgetHeaderG = 0,
      assignmentWidgetHeaderB = 0,
      assignmentWidgetHeaderAlpha = 0.8,
      assignmentWidgetHeaderWidth = 280,
      assignmentWidgetHeaderHeight = 25,
      assignmentWidgetBodyAlpha = 0.3,
      assignmentWidgetTitleOffsetX = 0,
      assignmentWidgetTitleOffsetY = 0,
      assignmentWidgetTitleSize = 14,
      assignmentWidgetHeaderFont = "Merfin Font 1",
      assignmentWidgetFontSize = 14,
      assignmentWidgetTitleSpacing = 0,
      assignmentWidgetLogoOffsetX = -14,
      assignmentWidgetLogoOffsetY = 7,
      assignmentWidgetLogoSize = 28,
      assignmentWidgetShowLogo = true,
      assignmentWidgetShowBorder = true,
      assignmentWidgetBorderR = 0.88,
      assignmentWidgetBorderG = 0.74,
      assignmentWidgetBorderB = 0.35,
      assignmentWidgetBorderThickness = 1,
      showRaidLeaderWidget = false,
      raidLeaderWidgetShowAlways = false,
      raidLeaderWidgetLoadOnlyInRaid = true,
      raidLeaderWidgetAlignment = "Down",
      raidLeaderWidgetX = -360,
      raidLeaderWidgetY = -120,
      raidLeaderWidgetPinned = false,
      raidLeaderWidgetHeaderR = 0,
      raidLeaderWidgetHeaderG = 0,
      raidLeaderWidgetHeaderB = 0,
      raidLeaderWidgetHeaderAlpha = 0.8,
      raidLeaderWidgetHeaderWidth = 220,
      raidLeaderWidgetHeaderHeight = 25,
      raidLeaderWidgetBodyAlpha = 0.28,
      raidLeaderWidgetTitleOffsetX = 0,
      raidLeaderWidgetTitleOffsetY = 0,
      raidLeaderWidgetTitleSize = 14,
      raidLeaderWidgetHeaderFont = "Merfin Font 1",
      raidLeaderWidgetFontSize = 14,
      raidLeaderWidgetTitleSpacing = 0,
      raidLeaderWidgetLogoOffsetX = -14,
      raidLeaderWidgetLogoOffsetY = 7,
      raidLeaderWidgetLogoSize = 28,
      raidLeaderWidgetShowLogo = true,
      raidLeaderWidgetShowBorder = true,
      raidLeaderWidgetBorderR = 0.88,
      raidLeaderWidgetBorderG = 0.74,
      raidLeaderWidgetBorderB = 0.35,
      raidLeaderWidgetBorderThickness = 1,
    },
  },
}
